services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock # 🔥 Add this here

    container_name: server
    env_file: server/.env
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - code-runner-network

  python-runner:
    build:
      context: .
      dockerfile: server/Dockerfiles/Dockerfile.python
    container_name: python-runner
    restart: always
    networks:
      - code-runner-network

  cpp-runner:
    build:
      context: .
      dockerfile: server/Dockerfiles/Dockerfile.cpp
    container_name: cpp-runner
    restart: always
    networks:
      - code-runner-network

  java-runner:
    build:
      context: .
      dockerfile: server/Dockerfiles/Dockerfile.java
    container_name: java-runner
    restart: always
    networks:
      - code-runner-network

  redis:
    image: redis:alpine
    container_name: quiz-exam-portal-redis-1
    ports:
      - "6379:6379"
    restart: always
    networks:
      - code-runner-network # Add this line
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  job-worker:
    build:
      context: .
      dockerfile: server/Dockerfiles/Dockerfile.worker
    container_name: job-worker
    restart: always
    privileged: true # Grants access to Docker inside this container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allows job-worker to use host Docker
      - /server/workers:/usr/src/app/workers  # ✅ Add this line here
    networks:
      - code-runner-network
    depends_on:
      - redis
      - rabbitmq
      - dind
  dind:
    image: docker:24.0.6-dind # Version can be updated
    container_name: docker-dind
    privileged: true # Enables Docker daemon inside the container
    environment:
      - DOCKER_TLS_CERTDIR=""
    networks:
      - code-runner-network
networks:
  code-runner-network:
    driver: bridge
