services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock # 🔥 Add this here

    container_name: server
    env_file: server/.env
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - quiz-exam-network
  redis:
    image: redis:alpine
    container_name: quiz-exam-portal-redis-1
    ports:
      - "6379:6379"
    restart: always
    networks:
      - quiz-exam-network # Add this line
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    
networks:
  quiz-exam-network:
    driver: bridge
